import {aggregate,zones,zoneAt} from './hotzones.js';
export const timingBonus=ms=>Math.max(-.16,.10-Math.abs(ms-850)/2500);
export function finalChance(base,ms,contest=0){return Math.max(.01,Math.min(.95,base+(ms===null?0:timingBonus(ms))-contest));}
export function setupGameplay({getState,shoot,move}){
const $=id=>document.getElementById(id);let charge=null,muted=true,audio=null,history=[],challenge=null,lastPair='',lastBounce=0;
function sound(kind){if(muted)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);const t=audio.currentTime;const hz={bounce:110,rim:460,squeak:1400,crowd:200}[kind];o.type=kind==='crowd'?'sawtooth':'sine';o.frequency.setValueAtTime(hz,t);o.frequency.exponentialRampToValueAtTime(hz/3,t+.2);g.gain.setValueAtTime(.045,t);g.gain.exponentialRampToValueAtTime(.001,t+.3);o.start();o.stop(t+.32);}catch{muted=true;$('sound').textContent='Sound unavailable';}}
function begin(){if(getState().busy||charge!==null||!allowed())return;charge=performance.now();sound('bounce');$('timing-note').textContent='Release in the green band';}
function release(){if(charge===null)return;const ms=performance.now()-charge;charge=null;shoot(ms);}
function allowed(){if(challenge?.ended){$('challenge-status').textContent+=' Start a new challenge or choose Free practice.';return false;}if(challenge?.mode==='clock'&&performance.now()>challenge.end){challenge.ended=true;status();return false;}return true;}
function status(){if(!challenge){$('challenge-status').textContent='Free practice · no limit';return;}const c=challenge;const left=Math.max(0,Math.ceil((c.end-performance.now())/1000));$('challenge-status').textContent=c.mode==='clock'?`${c.ended?'Finished':left+' seconds left'} · ${c.m} makes / ${c.n} shots`:c.mode==='three'?`${c.ended?'Finished':'Three-point contest'} · ${c.m} / ${c.n} made · 15 shots, 5 spots`:`${c.ended?'Challenge complete':'Race to 10'} · ${c.m} / 10 baskets · ${c.n} shots`;}
const spots=[[-23,2],[-18,20],[0,25],[18,20],[23,2]];
function start(){if(getState().busy)return;charge=null;const mode=$('challenge-mode').value;challenge=mode==='free'?null:{mode,m:0,n:0,end:performance.now()+60000,ended:false};if(mode==='three')move(...spots[0]);status();}
function record(shot){history.push(shot);if(challenge&&!challenge.ended){challenge.n++;challenge.m+=Number(shot.made);if(challenge.mode==='three'){challenge.ended=challenge.n>=15;if(!challenge.ended)move(...spots[Math.floor(challenge.n/3)]);}if(challenge.mode==='ten'&&challenge.m>=10)challenge.ended=true;}sound(shot.made?'crowd':'rim');renderHistory();status();}
function renderHistory(){const m=history.filter(s=>s.made).length;$('session-total').textContent=`${m} makes · ${history.length-m} misses · ${history.length?(100*m/history.length).toFixed(1):'0.0'}% · this visit, all selected shooters`;$('session-rows').innerHTML=zones.map(([id,name])=>{const a=history.filter(s=>zoneAt(s.x,s.y)===id),m=a.filter(s=>s.made).length;return `<tr><td>${name}</td><td>${m}</td><td>${a.length-m}</td><td>${a.length?(100*m/a.length).toFixed(1)+'%':'—'}</td></tr>`;}).join('');}
function compare(off,def){const key=off.id+':'+def.id;if(key===lastPair)return;lastPair=key;const a=aggregate(off.shots),b=aggregate(def.shots),fmt=z=>z.n?`${(100*z.m/z.n).toFixed(1)}% (${z.m}/${z.n})${z.n<20?' *':''}`:'—';$('compare-a').textContent=off.name;$('compare-b').textContent=def.name;$('compare-rows').innerHTML=zones.map(([id,name])=>`<tr><td>${name}</td><td>${fmt(a[id])}</td><td>${fmt(b[id])}</td></tr>`).join('');}
for(const id of ['charge-shot','court-charge']){const btn=$(id);btn.addEventListener('pointerdown',e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);begin();});btn.addEventListener('pointerup',release);btn.addEventListener('pointercancel',()=>charge=null);btn.addEventListener('keydown',e=>{if(['Space','Enter'].includes(e.code)){e.preventDefault();if(!e.repeat)begin();}});btn.addEventListener('keyup',e=>{if(['Space','Enter'].includes(e.code)){e.preventDefault();release();}});
}
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','BUTTON','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();if(!e.repeat)begin();}});document.addEventListener('keyup',e=>{if(e.code==='Space')release();});window.addEventListener('blur',()=>charge=null);document.addEventListener('visibilitychange',()=>{if(document.hidden)charge=null;});
$('sound').addEventListener('click',()=>{muted=!muted;$('sound').textContent=muted?'Enable sound':'Mute sound';$('sound').setAttribute('aria-pressed',String(!muted));sound('bounce');});$('challenge-start').addEventListener('click',start);$('clear-session').addEventListener('click',()=>{if(getState().busy)return;history=[];renderHistory();window.dispatchEvent(new Event('courtside:history-clear'));});renderHistory();status();
return {allowed,record,compare,sound,isCharging:()=>charge!==null,frame(time){if(charge!==null){const elapsed=time-charge;$('timing-meter').value=Math.min(1700,elapsed);if(elapsed>=1700)release();}if(challenge?.mode==='clock'&&!challenge.ended&&time>=challenge.end&&!getState().busy){challenge.ended=true;}status();if(!getState().busy&&time-lastBounce>1800){lastBounce=time;sound('bounce');}},feedback(ms,p){$('timing-note').textContent=ms===null?`Quick shot · ${(p*100).toFixed(1)}% final chance`:`${Math.abs(ms-850)<120?'Excellent release':ms<850?'Early release':'Late release'} · ${(p*100).toFixed(1)}% final chance`;},movementAllowed:()=>!challenge||challenge.mode!=='three'||challenge.ended};}
