import {isThree} from './model.js';
export const zones=[['rim','At the rim',0,0],['paint','Short paint',0,6],['shortL','Left short mid',-10,7],['shortC','Center short mid',0,12],['shortR','Right short mid',10,7],['longL','Left long mid',-18,10],['longC','Center long mid',0,20],['longR','Right long mid',18,10],['cornerL','Left corner 3',-23.5,2],['cornerR','Right corner 3',23.5,2],['wingL','Left wing 3',-19,23],['top','Top 3',0,29],['wingR','Right wing 3',19,23],['deep','Deep / backcourt',0,39]];
export function zoneAt(x,y){const d=Math.hypot(x,y),side=x<0?'L':'R';if(d>35)return 'deep';if(isThree(x,y)){if(Math.abs(x)>=22&&y<9)return 'corner'+side;return Math.abs(x)>Math.abs(y)*.58?'wing'+side:'top';}if(d<4)return 'rim';if(d<8)return 'paint';return (d<16?'short':'long')+(Math.abs(x)>Math.abs(y)*.58?side:'C');}
export function aggregate(shots){const result=Object.fromEntries(zones.map(([id])=>[id,{m:0,n:0}]));for(const [x,y,m] of shots){const z=result[zoneAt(x/10,y/10)];z.n++;z.m+=m;}return result;}
export function heat(z,league){if(!z.n)return 'No attempts';if(z.n<20||!league.n)return 'Small sample';const leagueRate=league.m/league.n;const smoothed=(z.m+20*leagueRate)/(z.n+20);const diff=smoothed-leagueRate;return diff>=.10?'Lethal':diff>=.05?'Hot':diff<=-.05?'Cold':'Neutral';}
const colors={'Cold':'#125bb8','Neutral':'#596a85','Hot':'#af354b','Lethal':'#653cdb','Small sample':'#364441','No attempts':'#202d2a'};
export function setupHotZones(data,onMove,preview){const league=aggregate(data.players.flatMap(p=>p.shots)),cache=new Map(),root=document.getElementById('hot-zones');let selected=null,last='';const role=document.getElementById('hot-role');const svg=document.getElementById('hot-chart'),mode=document.getElementById('hot-shot-mode');
function draw(off,def){selected={off,def};const p=role.value==='def'?def:off;const opponent=role.value==='def'?off:def;const key=[p.id,opponent.id,mode.value,document.getElementById('pressure').value].join(':');if(last===key)return;last=key;const projected=Object.fromEntries(zones.map(([id,name,x,y])=>[id,preview(p,opponent,x,y)]));document.getElementById('hot-mode-note').textContent=mode.value==='recorded'?'Chart: recorded FG%. Table also compares quick and excellent shots.':`Chart: ${mode.value==='quick'?'Quick Shot':'Excellent Release'} estimated chance against ${opponent.name}. Colors still describe historical hot zones.`;let stats=cache.get(p.id);if(!stats){stats=aggregate(p.shots);cache.set(p.id,stats);}document.getElementById('hot-title').textContent=p.name+' · hot zones';document.getElementById('hot-total').textContent=`${data.season} snapshot · ${p.fgm} / ${p.fga} total · ${p.fga?(100*p.fgm/p.fga).toFixed(1)+'%':'No attempts'}`;
let cells='';for(let y=-5.25;y<41.75;y+=.5){let start=-25,id=zoneAt(-24.75,y+.25);for(let x=-24.5;x<=25;x+=.5){const next=x===25?'end':zoneAt(x+.25,y+.25);if(next!==id){const label=heat(stats[id],league[id]);cells+=`<rect x="${(start+25)*10}" y="${(y+5.25)*10}" width="${(x-start)*10+.1}" height="5.1" fill="${colors[label]}"/>`;start=x;id=next;}}}
const pct=z=>z.n?(100*z.m/z.n).toFixed(1)+'%':'—';const simPct=n=>(100*n).toFixed(1)+'%';const shown=(id,z)=>mode.value==='recorded'?pct(z):simPct(projected[id][mode.value]);
svg.innerHTML=cells+`<g fill="none" stroke="#d4e2d8" stroke-width="2" opacity=".75"><path d="M1 1H499V469H1Z M170 0V190H330V0 M30 0V142.5A237.5 237.5 0 0 0 470 142.5V0"/><circle cx="250" cy="52.5" r="40"/><circle cx="250" cy="52.5" r="80"/><circle cx="250" cy="52.5" r="160"/><path d="M220 38H280"/><circle cx="250" cy="52.5" r="7.5"/></g>`+zones.map(([id,name,x,y])=>{const z=stats[id];return `<g transform="translate(${(x+25)*10},${(y+5.25)*10})"><title>${name}: ${shown(id,z)}, ${z.m} of ${z.n}. ${heat(z,league[id])}</title><rect x="-29" y="-13" width="58" height="34" rx="5" fill="#091511" opacity=".88"/><text text-anchor="middle" fill="white" font-size="13" font-weight="700">${shown(id,z)}</text><text y="14" text-anchor="middle" fill="#d3dfd9" font-size="10">${z.m}/${z.n}${z.n>0&&z.n<20?'*':''}</text></g>`;}).join('');
document.getElementById('hot-rows').replaceChildren(...zones.map(([id,name,x,y])=>{const z=stats[id],tr=document.createElement('tr'),button=document.createElement('button');button.textContent=name;button.addEventListener('click',()=>onMove(x,y));const td=document.createElement('td');td.append(button);tr.append(td);for(const text of [pct(z),`${z.m}/${z.n}`,heat(z,league[id]),pct(league[id]),simPct(projected[id].quick),simPct(projected[id].excellent)]){const cell=document.createElement('td');cell.textContent=text;tr.append(cell);}return tr;}));}
mode.addEventListener('change',()=>{last='';if(selected)draw(selected.off,selected.def);});role.addEventListener('change',()=>{last='';if(selected)draw(selected.off,selected.def);});svg.addEventListener('pointerdown',e=>{const pt=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse());onMove(pt.x/10-25,pt.y/10-5.25);});return {update:draw};}
