/** WebXR controls shared by tracked controllers, gaze and transient-pointer input. */
import * as THREE from './three.module.js';
export function setupVR({renderer,scene,camera,getState,onShoot,onMove,onPressure,onReset}) {
 const button=document.getElementById('enter-vr'),status=document.getElementById('vr-status');
 const rig=new THREE.Group();scene.add(rig);rig.add(camera);
 let session=null,entering=false,needsCenter=false,saved=null,lastText='',hudTimer=0,referenceType='local-floor';
 const targets=[],inputRays=new WeakMap(),controllers=[];
 const panel=new THREE.Group();panel.visible=false;rig.add(panel);
 const floor=new THREE.Plane(new THREE.Vector3(0,1,0),0);
 const board=document.createElement('canvas');board.width=1024;board.height=512;
 const ctx=board.getContext('2d'),texture=new THREE.CanvasTexture(board);texture.colorSpace=THREE.SRGBColorSpace;
 const info=new THREE.Mesh(new THREE.PlaneGeometry(1.7,.85),new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide}));info.position.set(0,1.65,-2.1);panel.add(info);
 function control(label,x,y,action){const c=document.createElement('canvas');c.width=384;c.height=100;const a=c.getContext('2d');a.fillStyle='#c8ee8d';a.fillRect(0,0,384,100);a.fillStyle='#17251b';a.font='bold 33px sans-serif';a.textAlign='center';a.textBaseline='middle';a.fillText(label,192,50);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(new THREE.PlaneGeometry(.52,.14),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));m.position.set(x,y,-1.81);m.userData.action=action;panel.add(m);targets.push(m);}
 control('SHOOT',-.57,1.05,()=>onShoot());control('PRESSURE',0,1.05,()=>onPressure());control('RESET',.57,1.05,()=>onReset());control('RECENTER',-.57,.83,()=>{needsCenter=true;});control('EXIT VR',.57,.83,()=>session?.end().catch(showError));
 renderer.xr.enabled=true;
 for(let i=0;i<2;i++){const controller=renderer.xr.getController(i);rig.add(controller);const geometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,0,-1)]);const line=new THREE.Line(geometry,new THREE.LineBasicMaterial({color:'#c8ee8d',transparent:true,opacity:.65}));line.scale.z=4;controller.add(line);controllers.push(controller);}
 function showError(e){status.textContent=`VR could not start: ${e.message||e}. You can still use desktop mode.`;}
 async function detect(){if(!window.isSecureContext){status.textContent='VR needs a trusted HTTPS address. Open the full-screen simulator on your headset over HTTPS.';button.textContent='HTTPS required for VR';return;}
 if(!navigator.xr){status.textContent='This browser does not expose WebXR. Use a compatible headset browser or a connected PC VR browser.';button.textContent='VR unavailable here';return;}
 try{const supported=await navigator.xr.isSessionSupported('immersive-vr');button.disabled=!supported;button.textContent=supported?'Enter VR':'No VR headset detected';status.textContent=supported?'Choose your players, then enter VR. Trigger or look-and-pinch selects the controls.':'Desktop mode is available. Connect a supported headset or open this app in its WebXR browser.';}catch(e){showError(e);}}
 function stateText(){const s=getState();return `${s.off} vs ${s.def}|${s.distance.toFixed(1)} ft - ${Math.round(s.probability*100)}% estimate|${s.makes} / ${s.attempts} made - ${s.pressure}|${s.result}`;}
 function drawHUD(){const text=stateText();if(text===lastText)return;lastText=text;ctx.fillStyle='#152921';ctx.fillRect(0,0,1024,512);ctx.fillStyle='#c8ee8d';ctx.textAlign='center';ctx.font='bold 38px sans-serif';ctx.fillText('COURTSIDE VR',512,58);ctx.fillStyle='#f0f6e9';ctx.font='30px sans-serif';text.split('|').forEach((t,i)=>ctx.fillText(t,512,113+i*46,970));ctx.font='24px sans-serif';ctx.fillStyle='#afbdaf';ctx.fillText('Aim at the floor + select to teleport.',512,330);ctx.fillText('Select SHOOT to take a probability-based shot.',512,368);texture.needsUpdate=true;}
 function rayFromEvent(event){const ref=renderer.xr.getReferenceSpace();if(!ref)return null;try{const pose=event.frame.getPose(event.inputSource.targetRaySpace,ref);if(!pose)return inputRays.get(event.inputSource)||null;rig.updateMatrixWorld(true);const mat=new THREE.Matrix4().fromArray(pose.transform.matrix).premultiply(rig.matrixWorld);const origin=new THREE.Vector3().setFromMatrixPosition(mat),direction=new THREE.Vector3(0,0,-1).transformDirection(mat);return new THREE.Ray(origin,direction);}catch{return inputRays.get(event.inputSource)||null;}}
 function onSelectStart(event){const ray=rayFromEvent(event);if(ray)inputRays.set(event.inputSource,ray.clone());}
 function onSelect(event){const state=getState();if(state.busy)return;const ray=rayFromEvent(event);if(!ray)return;const cast=new THREE.Raycaster(ray.origin,ray.direction,0,40);panel.updateMatrixWorld(true);const hit=cast.intersectObjects(targets,false)[0];if(hit){hit.object.userData.action();return;}const point=new THREE.Vector3();if(ray.intersectPlane(floor,point)&&Math.abs(point.x)<=25*.3048&&Math.abs(point.z)<=47*.3048){const head=renderer.xr.getCamera().getWorldPosition(new THREE.Vector3());rig.position.x+=point.x-head.x;rig.position.z+=point.z-head.z;rig.updateMatrixWorld(true);onMove(point.x/.3048,point.z/.3048+41.75);}}
 function restore(){session=null;entering=false;panel.visible=false;controllers.forEach(c=>c.visible=false);rig.position.set(0,0,0);rig.rotation.set(0,0,0);if(saved){camera.position.copy(saved.position);camera.quaternion.copy(saved.quaternion);}const s=getState();onMove(s.x,s.y);button.textContent='Enter VR';button.disabled=false;status.textContent='VR ended. Desktop controls restored.';}
 button.addEventListener('click',async()=>{if(session){await session.end();return;}if(entering||getState().busy)return;entering=true;button.disabled=true;let pending;
 try{pending=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor']});let space='local-floor';try{await pending.requestReferenceSpace(space);}catch{space='local';}referenceType=space;renderer.xr.setReferenceSpaceType(space);saved={position:camera.position.clone(),quaternion:camera.quaternion.clone()};camera.position.set(0,0,0);camera.quaternion.identity();session=pending;session.addEventListener('selectstart',onSelectStart);session.addEventListener('select',onSelect);session.addEventListener('end',restore,{once:true});await renderer.xr.setSession(session);needsCenter=true;panel.position.set(-1.65,referenceType==='local'?-1.65:0,0);panel.visible=true;controllers.forEach(c=>c.visible=true);button.textContent='Exit VR';button.disabled=false;entering=false;status.textContent='VR active. Use the in-world controls or your headset menu to exit.';lastText='';drawHUD();}
 catch(e){if(pending)await pending.end().catch(()=>{});restore();showError(e);}});
 function frame(time,frame){if(!renderer.xr.isPresenting||!frame)return;const pose=frame.getViewerPose(renderer.xr.getReferenceSpace());if(!pose)return;
 if(needsCenter){const s=getState(),p=pose.transform.position,q=pose.transform.orientation;const headEuler=new THREE.Euler().setFromQuaternion(new THREE.Quaternion(q.x,q.y,q.z,q.w),'YXZ');const yaw=Math.atan2(s.x,s.y);rig.rotation.y=yaw-headEuler.y;const offset=new THREE.Vector3(p.x,0,p.z).applyAxisAngle(new THREE.Vector3(0,1,0),rig.rotation.y);rig.position.set(s.x*.3048-offset.x,referenceType==='local'?1.65:0,(-41.75+s.y)*.3048-offset.z);needsCenter=false;}
 rig.updateMatrixWorld(true);if(time-hudTimer>150){drawHUD();hudTimer=time;}}
 function heldPosition(){const xrCamera=renderer.xr.getCamera();xrCamera.updateMatrixWorld(true);return xrCamera.localToWorld(new THREE.Vector3(0,-.28,-.6));}
 detect();return {frame,heldPosition,isActive:()=>renderer.xr.isPresenting};
}
